apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: generic-topology-processor
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
- apiGroups:
  - connectors.aiops.ibm.com
  resources:
  - connectorconfigurations
  verbs:
  - get
  - list    