apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connectorschema.yaml
  - microedgeconfiguration.yaml

configurations:
  - custom-images.yaml

images:
  - name: connector-event-template
    newName: hyc-cp4mcm-team-docker-local.artifactory.swg-devops.com/cp/aiopsedge/connector-event-template
    newTag: latest
