apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml

configurations:
  - namereference.yaml
  - varreference.yaml

images:
  - name: connector-event-template
    newName: hyc-cp4mcm-team-docker-local.artifactory.swg-devops.com/cp/aiopsedge/connector-event-template
    newTag: latest

vars:
  - name: SERVICE_NAME
    objref:
      kind: Service
      name: ibm-grpc-github-connector
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: SERVICE_NAMESPACE
    objref:
      kind: Service
      name: ibm-grpc-github-connector
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
