apiVersion: v1
kind: Service
metadata:
  name: java-grpc-connector-template
spec:
  selector:
    app: java-grpc-connector-template
    instance: connector
  ports:
    - protocol: TCP
      port: 443
      name: https
      targetPort: 9443
